### ISSUE TITLE
New Signal versions

### ISSUE THREAD

**Issue by acicovic** [portapps/signal-portable#10]
Hello there,

Signal have released a lot of new versions since 5.0 and the current version is 5.4.

Are there plans to keep this package updated in the future?

Thanks!

**Comment by crazy-max** [comment]
Done

**Comment by exec228** [comment]
Salut!

I have 

> Unhandled Promise Rejection
> 
> Error: Error: SQL: User version is 44 but the expected maximum version is 38. Did you try to start an old version of Signal?
>     at updateSchema ([REDACTED]\ts\sql\Server.js:1829:15)
>     at Object.initialize ([REDACTED]\ts\sql\Server.js:1859:9)
>     at MessagePort.<anonymous> ([REDACTED]\ts\sql\mainWorker.js:26:36)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
>     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
>     at Worker.<anonymous> ([REDACTED]\ts\sql\main.js:33:29)
>     at Worker.emit (events.js:315:20)
>     at MessagePort.<anonymous> (internal/worker.js:207:53)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
>     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)

with signal-portable-win64-5.14.0-5.7z and 5.25.1 data.

Is there any hope to get an update of binaries?

Thank you!

P.S. Tried with 5.17.1, but this version ultimately forced me to update to 5.25.1.
