### ISSUE TITLE
Error when linking my Android phone

### ISSUE THREAD

**Issue by WeberAlex** [portapps/signal-portable#13]
Hi CrazyMax,

Signal ver. 5.6.2-4 from [Portapps](https://portapps.io/app/signal-portable/) on Windows 10.

I receive a **Update Signal on your device to link your phone** message when I click on **Finishing linking phone** and it fails to connect.

![SCR_20210819_091101](https://user-images.githubusercontent.com/28292190/129987795-aeb0b6ec-833e-4c08-bfa5-08b788cc26b8.png)

Thanks for the support!

**Comment by HyperCriSiS** [comment]
Yes, same here. This version is too old to link with the actual Android version.

**Comment by crazy-max** [comment]
https://github.com/portapps/signal-portable/releases/tag/5.14.0-5
