### ISSUE TITLE
Update Signal 5.29.1

### ISSUE THREAD

**Issue by Pixeldorf** [portapps/signal-portable#14]
Hey,

will there bere a Update to Signaal 5.29.1?
The current portable Versio  doesn't pair with iOS Signal App.

Thank you <3

**Comment by tundrablasen** [comment]
For me the current old version of signal is not even starting anymore. seems like the whole release is broken. when starting the exe nothing happens

![image](https://user-images.githubusercontent.com/46343142/152120844-6f4f9538-821a-4b4b-937f-9cc5b28d998f.png)

**Comment by Rosmaninho** [comment]
Would love for an update for this app to work again. Can't install Signal on my admin locked work PC and wanted to use the portable app but it doesn't work.

**Comment by Rosmaninho** [comment]
Weird, I can't find it on portapps, or here in the release lists.

**Comment by tundrablasen** [comment]
> Weird, I can't find it on portapps, or here in the release lists.

He meant the original release. Not the portable release

**Comment by Rosmaninho** [comment]
Oh, I understood that they had updated this portable app version. I know that the desktop version is 5.30 now. I guess this project  is abandoned.

**Comment by vbprofi** [comment]
Hello,
I found out about signal portable today. The portable doesn't work for me either. Signal Desktop App is currently in version: Signal 5.31.1.
Will there be another update for the portable version?

**Comment by vbprofi** [comment]
ok, i found a solution to fix the problem:
1. download and install the signal desktop app.
2. download and install the portable signal app.
3. Copy the following folder contents from Desktop App to Portable APP: 
C:\Users\<user>\AppData\Local\Programs\signal-desktop\* to app\*

**Comment by Rosmaninho** [comment]
Thanks. That worked for me as well. :)
I would add the following steps were you left off:
4. Zip signal-portable folder.
5. Upload to cloud server of your choice and import to Admin-locked device.
6. Unzip Signal-portable and start using it.

**Comment by Pixeldorf** [comment]
> 

Thank you a lot. This works fine :*
