### ISSUE TITLE
Signal crashes on startup

### ISSUE THREAD

**Issue by drtrigon** [portapps/signal-portable#17]
#### Steps to reproduce this issue

1. Download [signal-portable-win64-5.34.0-6.7z](https://github.com/portapps/signal-portable/releases/download/5.34.0-6/signal-portable-win64-5.34.0-6.7z)
2. Unpack it
3. Run signal-portable.exe

#### Expected behaviour

Signal app should start and window should come up.

#### Actual behaviour

Error messagebox comes up stating: "Command failed"

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 5.34.0-6

**Operating system (ex. Windows 10 Pro 64 bits)** : Win 10

**Winver screenshot** : Version 1909 (Build 18363.2094)

### Screenshots

(none)

### Logs

```
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:118 > --------
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:119 > Operating System: Windows 10.0.18363
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:120 > Starting Signal 5.34.0-6 (portapps 3.4.0)...
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:121 > Release date: 2022/03/06 22:01:08
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:122 > Publisher: CrazyMax (https://github.com/portapps/signal-portable)
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:123 > Root path: C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:127 > Configuration:
common:
  disable_log: false
  args: []
  env: {}
  app_path: ""
app:
  cleanup: false

Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:168 > Process: C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\app\Signal.exe
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:169 > Args (config file): 
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:170 > Args (cmd line): 
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:171 > Args (hardcoded): --user-data-dir=C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\data
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:172 > Working dir: C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\app
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:173 > App path: C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\app
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:174 > Data path: C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\data
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:175 > Previous path: 
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:181 > Launching Signal
Mon, 07 Mar 2022 11:59:00 CET INF ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:191 > Exec C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\app\Signal.exe --user-data-dir=C:\Users\[REMOVED]\LocalDrive\Downloads\signal-portable-win64-5.34.0-6\data

Mon, 07 Mar 2022 11:59:08 CET FTL ..\..\..\..\runneradmin\go\pkg\mod\github.com\portapps\portapps\v3@v3.4.0\portapps.go:193 > Command failed error="exit status 1"
```

**Comment by crazy-max** [comment]
Was able to repro. Seems linked to electron.

**Comment by starsoccer** [comment]
+1 also happening for me

**Comment by tundrablasen** [comment]
have the same issue with the latest release of signal portable. start failed

**Comment by drtrigon** [comment]
Found that for win you can just unpack the original signal setup file. In there you have some file one named `app64.7z`, unpack it and run signal from it.
Currently no need for a portable app actually... ;)

**Comment by rkarp** [comment]
Just unpacking `app64.7z` will not give you a portable installation since it will write to your user directory.

However, if you replace the `app` directory of Signal Portable with the contents of `app64.7z`, Signal Portable works again.

**Comment by Murokam** [comment]
For the desktop version, I need a portable one.
I removed the "Command failed" error like this:
1. Unpacked signal-portable-win64-5.34.0-6.7z
2. Unpacked the original signal-desktop-win-5.35.0.exe file with the 7z archiver
3. Synchronized via Total Commander signal-desktop-win-5.35.0\$PLUGINSDIR app-64.7z with the folder into which I unpacked signal-portable-win64-5.34.0-6.7z.
Everything works, there are no more "Command failed" errors.

**Comment by drtrigon** [comment]
> However, if you replace the `app` directory of Signal Portable with the contents of `app64.7z`, Signal Portable works again.

So basically this issue is solved as the portable package just has to be built according to this recipe, correct?

**Comment by soldatchristi** [comment]
> Was able to repro. Seems linked to electron.

Can we use an older version or what's the work around?

**Comment by rkarp** [comment]
> Can we use an older version or what's the work around?

Older versions and even the current portable version are not even compatible anymore, it seems. One current workaround is:
1. Get the newest official Signal installer (`signal-desktop-win-5.37.0.exe`).
2. Open it with 7-Zip and unpack `app64.7z` from it.
3. In the Signal Portable folder, replace the contents of `app` with the contents of `app64.7z`.

**Comment by kingsqueens** [comment]
hi all, 
 I'm experiencing the same issue. happy to support investigation. (Windows 10.0.19042)
@rkarp: where could I get the v5.37 then I'll try and I'll take care to share feedback her for everyone
thanks

**Comment by kingsqueens** [comment]
> hi all, I'm experiencing the same issue. happy to support investigation. (Windows 10.0.19042) @rkarp: where could I get the v5.37 then I'll try and I'll take care to share feedback her for everyone thanks

I've found it and replacing app64 the app is running however to check if it's writing on other folders rather than the running folder.

**Comment by kingsqueens** [comment]
unfortunately the user system folder %APPDATA% has now signal folder so we need to find a fix to keep clean the system and running portable in the portable folder.
Happy to help let me know if I can support

**Comment by crazy-max** [comment]
Latest release should fix this issue: https://portapps.io/app/signal-portable/#download

**Comment by kingsqueens** [comment]
thanks @crazy-max 
It works and also it seems appdata folder is clean too now
