### ISSUE TITLE
Signal has expired - (portable version)

### ISSUE THREAD

**Issue by kingsqueens** [portapps/signal-portable#24]
### Behaviour
I'm using the latest portable version 5.38.0-7 and starting from 10.May.2022 the following issue occurs and the app cannot be used to write any message.

Issue: after the app is started the following error message appears and the app doesn't allow to write any message.

Error message: This version of Signal Desktop has expired. Please upgrade to the latest version to continue messaging.

#### Additional note:
@crazy-max : It looks like we need your help to release a new release asap thanks
How the portable app version could prevent the 'expiration' issue in the future? 
I have provided all required details and I'm available if you require any further information or clarifications
thanks

#### Steps to reproduce this issue

Steps:

    Open Signal
    Get message "This version of Signal Desktop has expired. Please upgrade to the latest version to continue messaging."
    Can't write messages

Actual Result: messages cannot be typed

Expected Result: message can be written

#### Expected behaviour

message can be written

#### Actual behaviour

messages cannot be sent

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 5.38.0-7 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Win10 Enterprise 20H2 64bit (OS Build 19042.1645)

**Winver screenshot** :
 Win10 Enterprise 20H2 64bit (OS Build 19042.1645)
### Screenshots

![2022-05-11_095509-001](https://user-images.githubusercontent.com/103311553/168423656-a2a9e4ff-691c-4c5a-9236-e893f2805843.png)

### Logs

[extract_signal-portable.log](https://github.com/portapps/signal-portable/files/8692834/extract_signal-portable.log)

**Comment by Basti77** [comment]
I have exactly the same problem since Tuesday, I can no longer use the desktop version at work.
An update is missing.
I have always used the portable version HERE because we use roaming profiles here and the "original" installed version has problems with %Appdata%" roaming.
At home I use the installed version and it works.

**Comment by dtantono** [comment]
Yeah, this portable needs to keep up with the upstream version.

**Comment by starsoccer** [comment]
@crazy-max any plans to update to latest version?

**Comment by tianxuanliu** [comment]
Same issue here.

**Comment by lucasnz** [comment]
Updating yourself is relatively straight forward:

1. Download the signal installer from signal.org
2. Don't run the installer, use something like 7zip to extract the contents.
3. Locate the file "app-64.7z" in $PLUGINSDIR
4. Extract the contents of this folder into the sub-folder "app" in your signal portable folder.

**Comment by dtantono** [comment]
@lucasnz Thanks for the workaround.

**Comment by therentabrain** [comment]
I wish there were a way to reach everyone still using Portable Signal, but this will have to do.  The two latest versions use a new encrypted key which depends on the logged in user, which means Signal Portable no longer functions.  As far as I can tell, there is no way around it currently.

Worse, if you try to use it on a different computer, in my experience it will break and you lose everything, even if you put it back on the original computer after that.

**Comment by eylenburg** [comment]
The workaround above still works for me. I last updated last week when my installation expired.

**Comment by therentabrain** [comment]
Oh yes, the workaround still works, but in my experience if you use it on more than one computer, it will fail to open, and then not be openable on the first computer either.  Is your experience different?

**Comment by eylenburg** [comment]
I don't know, I only use it on one computee

**Comment by therentabrain** [comment]
Some background information:
https://www.bleepingcomputer.com/news/security/signal-downplays-encryption-key-flaw-fixes-it-after-x-drama/

**Comment by eylenburg** [comment]
So does it mean the portable version will stop working?

Meanwhile they still dont have a way to password protect the desktop app...
