### ISSUE TITLE
Failed to Connect: Unexpected Error on Fresh Installation (Version 5.38.0) - Windows 10 Pro 64-bit

### ISSUE THREAD

**Issue by stevenfarless** [portapps/signal-portable#32]
#### Steps to reproduce this issue

1. Installed fresh signal-portable
2. Opened signal-portable

#### Expected behaviour

> App should connect and display QR code.

#### Actual behaviour

> Failed to connect, "Something went wrong! An unexpected error occurred. Please try again." Clicked "try again". App then displays the screen with "Scan this code in the Signal app on your phone..." but the QR code never generates, only the loading animation displays.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
App release 5.38.0 win64

**Operating system (ex. Windows 10 Pro 64 bits)** :
Edition	Windows 10 Pro
Version	22H2
OS build	19045.4046
Windows Feature Experience Pack 1000.19053.1000.0

**Winver screenshot** :

> 
![winver](https://github.com/portapps/signal-portable/assets/125781365/5e95d011-8de2-4feb-bcb9-ecbdd23df7ea)

### Screenshots

> If applicable, add screenshots to help explain your problem.
![sig went wrong](https://github.com/portapps/signal-portable/assets/125781365/cfcf063c-1b02-4dbf-bee2-f0427da17d0a)
![sig qr loading](https://github.com/portapps/signal-portable/assets/125781365/946dcb91-ec26-4889-bed2-606f3f056021)

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[signal-portable.log](https://github.com/portapps/signal-portable/files/14376403/signal-portable.log)

**Comment by vbprofi** [comment]
Hello,
The solution of the problem:
1. download the file: signal-portable-win64-5.38.0-7.7z
2. unpack / extract the file signal-portable-win64-5.38.0-7.7z to c:\signal-portable.
3. Download and install the original desktop signal app from here: https://signal.org/
4. Copy the original desktop app files into the portable signal apps directory. Folder named app.
xcopy /D /E /Y /I "C:\Users\<USER>\AppData\Local\Programs\signal-desktop" "c:\signal-portable\app"
5. Start the portable signal application: signal-portable.exe
6. now you can connect with smartphone via QR-Code scan.
